# Telecom Sales Data Analytics

## Import Required Libraries

In [1]:
# Import important libraries
import pandas as pd
import numpy as np

## Load and inspect data

In [2]:
# Load dataset
df = pd.read_csv("sales_data_raw.csv")

In [3]:
# view first five rows
df.head()

,Customer_ID,Date,Region,District,Channel,Product,Units_Sold,Unit_Price,Commission_MWK,Revenue_MWK
0,C1000,2022-01-01,North,Mzuzu,Agent,SIM,1,200,25.01702,200
1,C1001,2022-01-01,North,Mzuzu,Agent,SIM,1,200,25.01702,200
2,C1002,2022-01-01,North,Mzuzu,Agent,SIM,1,200,25.01702,200
3,C1003,2022-01-01,North,Mzuzu,Agent,SIM,2,200,25.01702,400
4,C1004,2022-01-01,North,Mzuzu,Agent,SIM,1,200,25.01702,200

In [4]:
# check dataset size (rows and columns)
df.shape

(2431255, 10)

In [5]:
# check data types
df.dtypes

Customer_ID           str
Date                  str
Region                str
District              str
Channel               str
Product               str
Units_Sold          int64
Unit_Price          int64
Commission_MWK    float64
Revenue_MWK         int64
dtype: object

In [6]:
# check summary statistic for numeric columns
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Units_Sold,2431255.0,1.499938,0.500000,1.000000,1.000000,1.000000,2.00000,2.000000
Unit_Price,2431255.0,266.908654,170.440252,100.000000,100.000000,200.000000,500.00000,500.000000
Commission_MWK,2431255.0,31.571958,23.249970,5.086079,13.583917,23.330719,44.27457,107.090178
Revenue_MWK,2431255.0,400.301079,300.609286,100.000000,200.000000,200.000000,500.00000,1000.000000

In [7]:
# Check for missing values
df.isnull().sum()

Customer_ID       0
Date              0
Region            0
District          0
Channel           0
Product           0
Units_Sold        0
Unit_Price        0
Commission_MWK    0
Revenue_MWK       0
dtype: int64

## Data Preprocessing

In [8]:
# Convert date to datetime format
df["Date"] = pd.to_datetime(df["Date"])

In [9]:
# Create time feeatues
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Month_Name"] = df["Date"].dt.strftime("%b")
df["Weekday"] = df["Date"].dt.day_name()

In [10]:
# Convert text columns to category
cols = ["Region", "District", "Channel", "Product"]

for col in cols:
    df[col] = df[col].astype("category")

## Create Business KPIs

In [11]:
# Revenue per Unit
df["Revenue_per_Unit"] = df["Revenue_MWK"] / df["Units_Sold"]

In [12]:
# Commission Rate
df["Commission_Rate"] = df["Commission_MWK"] / df["Revenue_MWK"]

In [13]:
# Sales Value Category
df["Sales_Category"] = pd.cut(
    df["Revenue_MWK"],
    bins=[0, 10000, 50000, 100000, 500000],
    labels=["Low", "Medium", "High", "Very High"]
)

## AGGREGATE the Data (for Excel & Power BI)

In [14]:
# Aggregation
df_summary = df.groupby(
    ["Year", "Month", "Region", "Channel", "Product"]
).agg({
    "Revenue_MWK": "sum",
    "Units_Sold": "sum",
    "Commission_MWK": "sum"
}).reset_index()

In [15]:
# Add KPI to summary
df_summary["Commission_Rate"] = (
    df_summary["Commission_MWK"] / df_summary["Revenue_MWK"]
)

## Save the Two Datasets

In [16]:
# Full clean dataset
df.to_csv("sales_clean.csv", index=False)

# Small dataset (for Excel & Power BI)
df_summary.to_csv("sales_summary.csv", index=False)